apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: python-job
        image: python-job:latest
        imagePullPolicy: IfNotPresent